// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: ping.proto

package ProtoMsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMD_SERVICE int32

const (
	CMD_SERVICE_INIT_SERVICE      CMD_SERVICE = 0
	CMD_SERVICE_G2S_DATA_TRANSFER CMD_SERVICE = 20003
	CMD_SERVICE_S2G_DATA_TRANSFER CMD_SERVICE = 20004
)

// Enum value maps for CMD_SERVICE.
var (
	CMD_SERVICE_name = map[int32]string{
		0:     "INIT_SERVICE",
		20003: "G2S_DATA_TRANSFER",
		20004: "S2G_DATA_TRANSFER",
	}
	CMD_SERVICE_value = map[string]int32{
		"INIT_SERVICE":      0,
		"G2S_DATA_TRANSFER": 20003,
		"S2G_DATA_TRANSFER": 20004,
	}
)

func (x CMD_SERVICE) Enum() *CMD_SERVICE {
	p := new(CMD_SERVICE)
	*p = x
	return p
}

func (x CMD_SERVICE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD_SERVICE) Descriptor() protoreflect.EnumDescriptor {
	return file_ping_proto_enumTypes[0].Descriptor()
}

func (CMD_SERVICE) Type() protoreflect.EnumType {
	return &file_ping_proto_enumTypes[0]
}

func (x CMD_SERVICE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD_SERVICE.Descriptor instead.
func (CMD_SERVICE) EnumDescriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{0}
}

type CMD_GAME int32

const (
	CMD_GAME_INIT_GAME CMD_GAME = 0
	CMD_GAME_PING      CMD_GAME = 1001
	CMD_GAME_PONG      CMD_GAME = 1002
)

// Enum value maps for CMD_GAME.
var (
	CMD_GAME_name = map[int32]string{
		0:    "INIT_GAME",
		1001: "PING",
		1002: "PONG",
	}
	CMD_GAME_value = map[string]int32{
		"INIT_GAME": 0,
		"PING":      1001,
		"PONG":      1002,
	}
)

func (x CMD_GAME) Enum() *CMD_GAME {
	p := new(CMD_GAME)
	*p = x
	return p
}

func (x CMD_GAME) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD_GAME) Descriptor() protoreflect.EnumDescriptor {
	return file_ping_proto_enumTypes[1].Descriptor()
}

func (CMD_GAME) Type() protoreflect.EnumType {
	return &file_ping_proto_enumTypes[1]
}

func (x CMD_GAME) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD_GAME.Descriptor instead.
func (CMD_GAME) EnumDescriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{1}
}

type CMD_DEV int32

const (
	CMD_DEV_INIT_DEV  CMD_DEV = 0
	CMD_DEV_C_DevPing CMD_DEV = 100001
	CMD_DEV_S_DevPing CMD_DEV = 100002
	CMD_DEV_C_DevInfo CMD_DEV = 101001
	CMD_DEV_S_DevInfo CMD_DEV = 101002
	CMD_DEV_S_OnLine  CMD_DEV = 102001
)

// Enum value maps for CMD_DEV.
var (
	CMD_DEV_name = map[int32]string{
		0:      "INIT_DEV",
		100001: "C_DevPing",
		100002: "S_DevPing",
		101001: "C_DevInfo",
		101002: "S_DevInfo",
		102001: "S_OnLine",
	}
	CMD_DEV_value = map[string]int32{
		"INIT_DEV":  0,
		"C_DevPing": 100001,
		"S_DevPing": 100002,
		"C_DevInfo": 101001,
		"S_DevInfo": 101002,
		"S_OnLine":  102001,
	}
)

func (x CMD_DEV) Enum() *CMD_DEV {
	p := new(CMD_DEV)
	*p = x
	return p
}

func (x CMD_DEV) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD_DEV) Descriptor() protoreflect.EnumDescriptor {
	return file_ping_proto_enumTypes[2].Descriptor()
}

func (CMD_DEV) Type() protoreflect.EnumType {
	return &file_ping_proto_enumTypes[2]
}

func (x CMD_DEV) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD_DEV.Descriptor instead.
func (CMD_DEV) EnumDescriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{2}
}

type G2S_DataTransfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnId   uint32 `protobuf:"varint,1,opt,name=ConnId,proto3" json:"ConnId,omitempty"`
	MsgID    int32  `protobuf:"varint,2,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	DataJson string `protobuf:"bytes,4,opt,name=DataJson,proto3" json:"DataJson,omitempty"`
}

func (x *G2S_DataTransfer) Reset() {
	*x = G2S_DataTransfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2S_DataTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2S_DataTransfer) ProtoMessage() {}

func (x *G2S_DataTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2S_DataTransfer.ProtoReflect.Descriptor instead.
func (*G2S_DataTransfer) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{0}
}

func (x *G2S_DataTransfer) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *G2S_DataTransfer) GetMsgID() int32 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *G2S_DataTransfer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *G2S_DataTransfer) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type S2G_DataTransfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnId   uint32 `protobuf:"varint,1,opt,name=ConnId,proto3" json:"ConnId,omitempty"`
	MsgID    int32  `protobuf:"varint,2,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	DataJson string `protobuf:"bytes,4,opt,name=DataJson,proto3" json:"DataJson,omitempty"`
}

func (x *S2G_DataTransfer) Reset() {
	*x = S2G_DataTransfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2G_DataTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2G_DataTransfer) ProtoMessage() {}

func (x *S2G_DataTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2G_DataTransfer.ProtoReflect.Descriptor instead.
func (*S2G_DataTransfer) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{1}
}

func (x *S2G_DataTransfer) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *S2G_DataTransfer) GetMsgID() int32 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *S2G_DataTransfer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *S2G_DataTransfer) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type C2S_Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping int32 `protobuf:"varint,1,opt,name=Ping,proto3" json:"Ping,omitempty"`
}

func (x *C2S_Ping) Reset() {
	*x = C2S_Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Ping) ProtoMessage() {}

func (x *C2S_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Ping.ProtoReflect.Descriptor instead.
func (*C2S_Ping) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_Ping) GetPing() int32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

type S2C_Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong int32 `protobuf:"varint,2,opt,name=Pong,proto3" json:"Pong,omitempty"`
}

func (x *S2C_Pong) Reset() {
	*x = S2C_Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Pong) ProtoMessage() {}

func (x *S2C_Pong) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Pong.ProtoReflect.Descriptor instead.
func (*S2C_Pong) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_Pong) GetPong() int32 {
	if x != nil {
		return x.Pong
	}
	return 0
}

type C2S_DevPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *C2S_DevPing) Reset() {
	*x = C2S_DevPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_DevPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DevPing) ProtoMessage() {}

func (x *C2S_DevPing) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DevPing.ProtoReflect.Descriptor instead.
func (*C2S_DevPing) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{4}
}

func (x *C2S_DevPing) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *C2S_DevPing) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type S2C_DevPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *S2C_DevPing) Reset() {
	*x = S2C_DevPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_DevPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_DevPing) ProtoMessage() {}

func (x *S2C_DevPing) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_DevPing.ProtoReflect.Descriptor instead.
func (*S2C_DevPing) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_DevPing) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *S2C_DevPing) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type C2S_DevInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Group   string `protobuf:"bytes,2,opt,name=Group,proto3" json:"Group,omitempty"`
	AppKey  string `protobuf:"bytes,3,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	Ip      string `protobuf:"bytes,4,opt,name=Ip,proto3" json:"Ip,omitempty"`
	IpLocal string `protobuf:"bytes,5,opt,name=IpLocal,proto3" json:"IpLocal,omitempty"`
	Port    int32  `protobuf:"varint,6,opt,name=Port,proto3" json:"Port,omitempty"`
	ConnId  int32  `protobuf:"varint,7,opt,name=ConnId,proto3" json:"ConnId,omitempty"`
}

func (x *C2S_DevInfo) Reset() {
	*x = C2S_DevInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_DevInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_DevInfo) ProtoMessage() {}

func (x *C2S_DevInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_DevInfo.ProtoReflect.Descriptor instead.
func (*C2S_DevInfo) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_DevInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *C2S_DevInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *C2S_DevInfo) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *C2S_DevInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *C2S_DevInfo) GetIpLocal() string {
	if x != nil {
		return x.IpLocal
	}
	return ""
}

func (x *C2S_DevInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *C2S_DevInfo) GetConnId() int32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

type S2C_DevInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32          `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Msg     string         `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	DevList []*C2S_DevInfo `protobuf:"bytes,3,rep,name=DevList,proto3" json:"DevList,omitempty"`
}

func (x *S2C_DevInfo) Reset() {
	*x = S2C_DevInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_DevInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_DevInfo) ProtoMessage() {}

func (x *S2C_DevInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_DevInfo.ProtoReflect.Descriptor instead.
func (*S2C_DevInfo) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{7}
}

func (x *S2C_DevInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *S2C_DevInfo) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *S2C_DevInfo) GetDevList() []*C2S_DevInfo {
	if x != nil {
		return x.DevList
	}
	return nil
}

type S2C_OnLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32          `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Msg     string         `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	DevList []*C2S_DevInfo `protobuf:"bytes,3,rep,name=DevList,proto3" json:"DevList,omitempty"`
}

func (x *S2C_OnLine) Reset() {
	*x = S2C_OnLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_OnLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_OnLine) ProtoMessage() {}

func (x *S2C_OnLine) ProtoReflect() protoreflect.Message {
	mi := &file_ping_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_OnLine.ProtoReflect.Descriptor instead.
func (*S2C_OnLine) Descriptor() ([]byte, []int) {
	return file_ping_proto_rawDescGZIP(), []int{8}
}

func (x *S2C_OnLine) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *S2C_OnLine) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *S2C_OnLine) GetDevList() []*C2S_DevInfo {
	if x != nil {
		return x.DevList
	}
	return nil
}

var File_ping_proto protoreflect.FileDescriptor

var file_ping_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x10,
	0x47, 0x32, 0x53, 0x5f, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x70,
	0x0a, 0x10, 0x53, 0x32, 0x47, 0x5f, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73,
	0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4a, 0x73, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4a, 0x73, 0x6f, 0x6e,
	0x22, 0x1e, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x5f, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x69, 0x6e, 0x67,
	0x22, 0x1e, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x6e, 0x67,
	0x22, 0x37, 0x0a, 0x0b, 0x43, 0x32, 0x53, 0x5f, 0x44, 0x65, 0x76, 0x50, 0x69, 0x6e, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x37, 0x0a, 0x0b, 0x53, 0x32, 0x43,
	0x5f, 0x44, 0x65, 0x76, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x22, 0xa5, 0x01, 0x0a, 0x0b, 0x43, 0x32, 0x53, 0x5f, 0x44, 0x65, 0x76, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x70,
	0x70, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x49, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x0b, 0x53, 0x32,
	0x43, 0x5f, 0x44, 0x65, 0x76, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4d, 0x73, 0x67, 0x12, 0x26, 0x0a, 0x07, 0x44, 0x65, 0x76, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x32, 0x53, 0x5f, 0x44, 0x65, 0x76, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x07, 0x44, 0x65, 0x76, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x0a, 0x53,
	0x32, 0x43, 0x5f, 0x4f, 0x6e, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4d, 0x73, 0x67, 0x12, 0x26, 0x0a, 0x07, 0x44, 0x65, 0x76, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x32, 0x53, 0x5f, 0x44, 0x65, 0x76, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x07, 0x44, 0x65, 0x76, 0x4c, 0x69, 0x73, 0x74, 0x2a, 0x51, 0x0a, 0x0b, 0x43,
	0x4d, 0x44, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e,
	0x49, 0x54, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x11,
	0x47, 0x32, 0x53, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45,
	0x52, 0x10, 0xa3, 0x9c, 0x01, 0x12, 0x17, 0x0a, 0x11, 0x53, 0x32, 0x47, 0x5f, 0x44, 0x41, 0x54,
	0x41, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x10, 0xa4, 0x9c, 0x01, 0x2a, 0x2f,
	0x0a, 0x08, 0x43, 0x4d, 0x44, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e,
	0x49, 0x54, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x04, 0x50, 0x49, 0x4e,
	0x47, 0x10, 0xe9, 0x07, 0x12, 0x09, 0x0a, 0x04, 0x50, 0x4f, 0x4e, 0x47, 0x10, 0xea, 0x07, 0x2a,
	0x6b, 0x0a, 0x07, 0x43, 0x4d, 0x44, 0x5f, 0x44, 0x45, 0x56, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e,
	0x49, 0x54, 0x5f, 0x44, 0x45, 0x56, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x09, 0x43, 0x5f, 0x44, 0x65,
	0x76, 0x50, 0x69, 0x6e, 0x67, 0x10, 0xa1, 0x8d, 0x06, 0x12, 0x0f, 0x0a, 0x09, 0x53, 0x5f, 0x44,
	0x65, 0x76, 0x50, 0x69, 0x6e, 0x67, 0x10, 0xa2, 0x8d, 0x06, 0x12, 0x0f, 0x0a, 0x09, 0x43, 0x5f,
	0x44, 0x65, 0x76, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x89, 0x95, 0x06, 0x12, 0x0f, 0x0a, 0x09, 0x53,
	0x5f, 0x44, 0x65, 0x76, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x8a, 0x95, 0x06, 0x12, 0x0e, 0x0a, 0x08,
	0x53, 0x5f, 0x4f, 0x6e, 0x4c, 0x69, 0x6e, 0x65, 0x10, 0xf1, 0x9c, 0x06, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ping_proto_rawDescOnce sync.Once
	file_ping_proto_rawDescData = file_ping_proto_rawDesc
)

func file_ping_proto_rawDescGZIP() []byte {
	file_ping_proto_rawDescOnce.Do(func() {
		file_ping_proto_rawDescData = protoimpl.X.CompressGZIP(file_ping_proto_rawDescData)
	})
	return file_ping_proto_rawDescData
}

var file_ping_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ping_proto_goTypes = []interface{}{
	(CMD_SERVICE)(0),         // 0: CMD_SERVICE
	(CMD_GAME)(0),            // 1: CMD_GAME
	(CMD_DEV)(0),             // 2: CMD_DEV
	(*G2S_DataTransfer)(nil), // 3: G2S_DataTransfer
	(*S2G_DataTransfer)(nil), // 4: S2G_DataTransfer
	(*C2S_Ping)(nil),         // 5: C2S_Ping
	(*S2C_Pong)(nil),         // 6: S2C_Pong
	(*C2S_DevPing)(nil),      // 7: C2S_DevPing
	(*S2C_DevPing)(nil),      // 8: S2C_DevPing
	(*C2S_DevInfo)(nil),      // 9: C2S_DevInfo
	(*S2C_DevInfo)(nil),      // 10: S2C_DevInfo
	(*S2C_OnLine)(nil),       // 11: S2C_OnLine
}
var file_ping_proto_depIdxs = []int32{
	9, // 0: S2C_DevInfo.DevList:type_name -> C2S_DevInfo
	9, // 1: S2C_OnLine.DevList:type_name -> C2S_DevInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ping_proto_init() }
func file_ping_proto_init() {
	if File_ping_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ping_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2S_DataTransfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2G_DataTransfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_DevPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_DevPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_DevInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_DevInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_OnLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ping_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ping_proto_goTypes,
		DependencyIndexes: file_ping_proto_depIdxs,
		EnumInfos:         file_ping_proto_enumTypes,
		MessageInfos:      file_ping_proto_msgTypes,
	}.Build()
	File_ping_proto = out.File
	file_ping_proto_rawDesc = nil
	file_ping_proto_goTypes = nil
	file_ping_proto_depIdxs = nil
}
