// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	game "go-cms/app/game/cmd/api/internal/handler/game"
	"go-cms/app/game/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/game/getRank",
				Handler: game.GetRankHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/game/getShop",
				Handler: game.GetShopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/game/getNotify",
				Handler: game.GetNotifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/game/getBattle",
				Handler: game.GetBattleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/game/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/game/getPack",
				Handler: game.GetPackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/game/useGoods",
				Handler: game.UseGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/game/changeScore",
				Handler: game.ChangeScoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/game/buyGoods",
				Handler: game.BuyGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/game/getMyBattle",
				Handler: game.GetMyBattleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/game/v1"),
	)
}
