global:
  scrape_interval:
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'usercenter-rpc'
    static_configs:
      - targets: ['gogame:10019']
        labels:
          job: usercenter-rpc
          app: usercenter-rpc
          env: dev

  - job_name: 'mqueue-job'
    static_configs:
      - targets: [ 'gogame:20019' ]
        labels:
          job: mqueue-job
          app: mqueue-job
          env: dev

  - job_name: 'basic-api'
    static_configs:
      - targets: [ 'gogame:10029' ]
        labels:
          job: basic-api
          app: basic-api
          env: dev

  - job_name: 'basic-rpc'
    static_configs:
      - targets: [ 'gogame:20029' ]
        labels:
          job: order-rpc
          app: order-rpc
          env: dev  

  - job_name: 'game-api'
    static_configs:
      - targets: [ 'gogame:10039' ]
        labels:
          job: game-api
          app: game-api
          env: dev

  - job_name: 'game-rpc'
    static_configs:
      - targets: [ 'gogame:20039' ]
        labels:
          job: game-rpc
          app: game-rpc
          env: dev
  
 

